const employee = [
  {
    id: 1,
    firstName: "Aarav",
    email: "e@e.com",
    password: "123",
    tasks: [
      {
        title: "Design Homepage",
        description: "Create a responsive design for the homepage.",
        date: "2023-10-15",
        category: "Design",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Login Bug",
        description: "Resolve the issue with the login button not working.",
        date: "2023-10-16",
        category: "Development",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Write API Documentation",
        description: "Document the new API endpoints for the backend team.",
        date: "2023-10-17",
        category: "Documentation",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: { active: 2, newtask: 1, completed: 1, failed: 0 },
  },
  {
    id: 2,
    firstName: "Vihaan",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Test Payment Gateway",
        description: "Ensure the payment gateway integration works correctly.",
        date: "2023-10-15",
        category: "Testing",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update User Dashboard",
        description: "Add new features to the user dashboard.",
        date: "2023-10-16",
        category: "Development",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Review Code Pull Request",
        description: "Review and merge the latest pull request from the team.",
        date: "2023-10-17",
        category: "Code Review",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare Sprint Report",
        description: "Compile and present the sprint report to stakeholders.",
        date: "2023-10-18",
        category: "Reporting",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: { active: 3, newtask: 1, completed: 1, failed: 0 },
  },
  {
    id: 3,
    firstName: "Kabir",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Optimize Database Queries",
        description: "Improve the performance of slow database queries.",
        date: "2023-10-15",
        category: "Database",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Create Marketing Campaign",
        description: "Plan and execute a new marketing campaign.",
        date: "2023-10-16",
        category: "Marketing",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix CSS Issues",
        description: "Resolve CSS alignment issues on the product page.",
        date: "2023-10-17",
        category: "Design",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Deploy New Feature",
        description: "Deploy the new search feature to production.",
        date: "2023-10-18",
        category: "DevOps",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Write Unit Tests",
        description: "Write unit tests for the new authentication module.",
        date: "2023-10-19",
        category: "Testing",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: { active: 3, newtask: 1, completed: 1, failed: 1},
  },
  {
    id: 4,
    firstName: "Ishaan",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Plan Team Meeting",
        description: "Organize the agenda for the next team meeting.",
        date: "2023-10-15",
        category: "Management",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update Privacy Policy",
        description: "Revise the privacy policy to comply with new regulations.",
        date: "2023-10-16",
        category: "Legal",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Broken Links",
        description: "Identify and fix broken links on the website.",
        date: "2023-10-17",
        category: "Maintenance",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Create User Guides",
        description: "Write user guides for the new software features.",
        date: "2023-10-18",
        category: "Documentation",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Monitor Server Health",
        description: "Check server logs and ensure everything is running smoothly.",
        date: "2023-10-19",
        category: "DevOps",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Design New Logo",
        description: "Create a new logo for the company rebranding.",
        date: "2023-10-20",
        category: "Design",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: { active: 5, newtask: 1, completed: 1, failed: 0 },
  },
  {
    id: 5,
    firstName: "Aryan",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Analyze Sales Data",
        description: "Analyze sales data to identify trends and opportunities.",
        date: "2023-10-15",
        category: "Analytics",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Create Social Media Posts",
        description: "Design and schedule posts for the company's social media accounts.",
        date: "2023-10-16",
        category: "Marketing",
        active: true,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Bug in Checkout Flow",
        description: "Resolve the issue with the checkout process.",
        date: "2023-10-17",
        category: "Development",
        active: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare Budget Report",
        description: "Compile the quarterly budget report for the finance team.",
        date: "2023-10-18",
        category: "Finance",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Train New Intern",
        description: "Provide training to the new intern on company processes.",
        date: "2023-10-19",
        category: "HR",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update Employee Handbook",
        description: "Revise the employee handbook with the latest policies.",
        date: "2023-10-20",
        category: "HR",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Organize Team Building Event",
        description: "Plan and execute a team-building event for the company.",
        date: "2023-10-21",
        category: "HR",
        active: true,
        newtask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: { active: 6, newtask: 1, completed: 1, failed: 0 },
  },
];

const admin = {
  id: 100,
  firstName: "Admin", 
  email: "admin@example.com",
  password: "123",
};

export const setLocalStorage = () => {
  localStorage.setItem("admin", JSON.stringify(admin));
  localStorage.setItem("employee", JSON.stringify(employee));
};

export const getLocalStorage = () => {
  const admin = JSON.parse(localStorage.getItem("admin"));
  const employee = JSON.parse(localStorage.getItem("employee"));
  return { admin, employee };
}